### ISSUE TITLE
Bump to libreoffice-6.3

### ISSUE THREAD

**Issue by Elleni57** [xdch47/gpo-xdch47#2]
Hi xdch47, 

after updating I still can access libreoffice-administration console, but cannot open documents within my nextcloud instance. 

Thanks in advance if you like to share an updated ebuild. :)

loolwsd.log: 
http://dpaste.com/1BM1W1E

**Comment by xdch47** [comment]
Hi,
yes the package build isn't perfect yet. (e.g. `/tmp, /usr, /var/lib` must be on the same partition for the hardlinks).

however, i think it worked for me after reemerging+updating the template  (`emerge -avO1 libreoffice-online; loolconfig update-system-template`).

still, i would prefer that the `libreoffice-online` builds the `libreoffice office core` with the version matched, this would overcome the update issues + the hardlink problem. -  but, haven't had time yet to adapted the pkgbuild…

**Comment by xdch47** [comment]
no further updates on the libreoffice-6-3 branch here: https://gerrit.libreoffice.org/plugins/gitiles/online/+/libreoffice-6-3

**Comment by Elleni57** [comment]
While re-installing/migrating my vserver, I tested it again, and can report that it works with both, stable libreoffice 6.2.x and also with unstable 6.3.3.2

**Comment by Elleni57** [comment]
Hi xdch47,

I became aware of this 
https://documentation.libreoffice.org/en/english-documentation/ so I 
wanted to ask, if you maybe find some time to create an updated ebuild? 
Thanks in advance. :)

Best regards


Am 2019-10-03 11:24, schrieb xdch47:

**Comment by Elleni57** [comment]
Hi xdch47,

I became aware of this https://documentation.libreoffice.org/en/english-documentation/ so I wanted to ask, if you maybe find some time to create an updated ebuild? Thanks in advance. :)

Best regards

**Comment by xdch47** [comment]
just tried the  libreoffice-6.3.0.0.beta1 version.
packaging is difficult since npm files are missing in the repo (works with `FEATURE="-network-sandbox"`).
from a first look i can just say that translation is missing at a couple of points (menus have been changed a little) and zooming is limited to (100% and 200%) on spread sheets - [strange - is this a feature??].
download as pdf still crashes. page load might be slightly faster. UI might look a bit more "modern". 

so far no difference - is are there new features you are looking forward to ?

**Comment by Elleni57** [comment]
Hi xdch47, and thanks for looking into it! I am not looking forward to any particular feature - just wanted to stay up to date, but after what you describe, it might be worth waiting a stabler version? I leave it up to you. Thanks again ;)

**Comment by xdch47** [comment]
Hi, just bump to `7.0.1.1`. As upstream renamed the package to `loolwsd`, I did the same for the ebuild.
So **remove** libreoffice-online (and clean up the files in `/etc/libreoffice-online`, `/var/lib/{,cache/}libreoffice-online`, `/var/log/libreoffice-online}` before installing the new version.
Closed by: c6d3ba7
