### ISSUE TITLE
Adding fonts to libreoffice (online)

### ISSUE THREAD

**Issue by Elleni57** [xdch47/gpo-xdch47#4]
I can emerge corefonts and other font packages on my gentoo server, and they appear in the fontslist within libreoffice-online. But as soon as one new font is chosen, the text in the document disapears. May this be a problem with access rights on the fonts? Do you happen to know how to correctly install fonts for libreoffice-online?

**Comment by xdch47** [comment]
after install new fonts I think you have to rerun `loolconfig update-system-template`, to make them visible to lool.

**Comment by Elleni57** [comment]
you are right. running loolconfig update-system-template fixed it. Thank you :)
